sapphiredev/website

- docs/Guide/CLI/getting-started.mdx
- docs/Guide/plugins/Logger/getting-started.mdx
I added that warning because I saw more than 3 people using older versions of Node and having issues.
> Fix the typo on `plugin-logger`'s import and add a warning to CLI guide

- docs/Guide/arguments/built-in-arguments.mdx
https://github.com/sapphiredev/framework/pull/354
> feat(guide): enum argument

- docs/General/Welcome.mdx
I also replaced "the" with "this" as a way to confirm that the version we're talking about is the one mentioned earlier as the one of the documentation
> fix: a confusion about latest and next versions

- docs/Guide/listeners/creating-your-own-listeners.mdx
- docs/Guide/preconditions/creating-your-own-preconditions.mdx
The "Preconditions" part of the guide comes before the "Listeners" one, so the narrative "Just as we did in (...) Creating Listeners" seems incorrect.
And vice-versa
> fix: guide order and references to previous parts

- docs/Guide/arguments/using-arguments.mdx
The option is not used right away but later, so mentioning it here is confusing
> fix: remove `times` when not necessary

- docs/Guide/plugins/i18next/getting-started.mdx
Current example raises -
```ts
Expected 2-3 arguments, but got 1.ts(2554)
[functions.d.ts(33, 185): ]()An argument for 'key' was not provided.
```
Which is because example isn't specifying to resolve key for what, fixed it by specifying `message.guild`.
> fix(guide-i18n): `resolveKey` example

- docs/General/Welcome.mdx
- docs/Guide/getting-started/getting-started-with-sapphire.mdx
As the framework only supports DiscordJS v13 (not latest: v14), it would be appropriate to set the working version in the documentation example.
> docs: clarify discordjs version limitation

- docs/Guide/listeners/listening-to-events-emitted-by-other-emitters.mdx
When compiling the example code I get an error `Cannot find name 'container'. Did you mean the instance member 'this.container'?` and the fix was to add an import for `container`
> fix: add missing import in exapmle

- docs/Guide/preconditions/creating-your-own-preconditions.mdx
The old module augmenting link takes you to the wrong lines since the preconditions example has been updated for v3.
This also adds a code snippet and moves it next to the example code into the previous section. Readers previously needed to dig backwards if they ran into the issue in the "Using Preconditions in Commands" section, so this change should make it easier to follow. The TODO is still there.
> docs: update preconditions-augment link and move next to example

- docs/Guide/CLI/generating-components.md
Adds the 2 new templates for CLI components and updated `command` component to `messagecommand`.
> docs: update component templates and example

- docs/Guide/application-commands/application-command-registry/registering-chat-input-commands.mdx
- docs/Guide/application-commands/what-are-application-commands.mdx
- docs/Guide/getting-started/creating-a-basic-app-command.mdx
- docs/Guide/getting-started/creating-a-basic-command.mdx
- docs/Guide/getting-started/creating-a-basic-context-menu-command.mdx
Now that #199 has been merged, the application command sections in the "Getting Started" guide should be updated so new readers are aware of where to get detailed information.
This also adds a "What are application commands?" section to smooth the transition into reading about application command registries.
> docs: update getting started app command guides

- docs/Guide/application-commands/application-command-registry/registering-chat-input-commands.mdx
The previous link https://discordjs.guide/interactions/slash-commands.html#options sends you to a 404 page, it seems that the new link is: https://discordjs.guide/slash-commands/advanced-creation.html#option-types
> fix: update broken discord.js guide link

- docs/Guide/getting-started/updating-from-v3-to-v4.mdx
The DiscordJS guide does not cover requiring `GatewayIntentBits.MessageContent` when upgrading to v14, and it caused me issues with message commands earlier.
I got the information about the contents in messages from: https://discordjs.guide/popular-topics/intents.html#enabling-intents
> docs: add information on 'MessageContent' intent

- docs/Guide/preconditions/reporting-precondition-failure.mdx
Fixed a typo in which `contextMenuCommandDenied` was spelt incorrectly
> fix: typo in reporting precondition failure

- docs/Guide/additional-information/using-and-extending-container.mdx
The intents seem like they haven't been updated for discord.js v14, so I updated them to use enums.
I'm guessing updating this https://www.sapphirejs.dev/docs/Guide/getting-started/updating-from-v2-to-v3#events doesn't matter as it's for Sapphire v3.
> docs: update intents to use enums

- docs/Guide/preconditions/reporting-precondition-failure.mdx
The current [Reporting precondition failure](https://www.sapphirejs.dev/docs/Guide/preconditions/reporting-precondition-failure) documentation for precondition has a section teaching how to how [Ignore Precondition Failures](https://www.sapphirejs.dev/docs/Guide/preconditions/reporting-precondition-failure#ignoring-precondition-failures). 
That works like a charm if the precondition is for a command that is not an interaction command but every interaction requires a reply, if you don't provide it and ignore the command in the precondition Discord will understand that your command does not respond, and inform the user. 
This caution adds an alert for people who are implementing it for a Slash Command (interaction)
> docs: add a caution about reply requires for interaction

- docs/Guide/preconditions/creating-your-own-preconditions.mdx
The directory was renamed from `with-typescript-recommended` to `with-typescript-complete` with [`8edc19c`](https://github.com/sapphiredev/examples/commit/8edc19c0c41eefb8730baeb1bb13b5df4e3f7d4f), but the link wasn't updated.
> docs: updated link to TS template precondition

- docs/Guide/interaction-handlers/autocomplete.mdx
Change autoCompleteRun to the correct method name autocompleteRun
> docs: fix typo ("autoCompleteRun" to "autocompleteRun")

- docs/Guide/getting-started/creating-a-basic-app-command.mdx
Fixed TypeScript code. The function `chatInputRun` must be overridden as it is present in the Command class, that the PingCommand class extends from.
> docs: fix TypeScript Code In Guide

- docs/Guide/commands/application-commands/what-are-application-commands.mdx
Fixes #292
Fix the broken relative link in the documentation.
* Update the link "Application Command Registry" in `docs/Guide/commands/application-commands/what-are-application-commands.mdx` to use the correct relative path.
* Ensure the link redirects to `docs/Guide/commands/application-commands/application-command-registry/what-is-it`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/sapphiredev/website/pull/294?shareId=b2418e34-afc9-42d9-8d9e-f9e962513ea6).
> fix: broken links in documentation

- docs/Guide/commands/application-commands/application-command-registry/registering-context-commands.mdx
This pull request addresses an issue in the context menu interaction where the method `isUserContextMenu` does not exist on type `ContextMenuCommandInteraction<CacheType>`. The method has been correctly updated to `isUserContextMenuCommand`.
- Updated the method from `isUserContextMenu` to `isUserContextMenuCommand` in the `contextMenuRun`
> Fix issue with `isUserContextMenu` method in context menu interaction documentation
